[build]
  command = "npm install && npm run setup && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "14"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-emails"
