[build]
  command = "npm install && npm run createfiles && npm run initcomponents && npm run setup && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "False"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-emails"
