[build]
  command = "npm install && npm run presetup && npm run setup && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  CI = "False"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-emails"
